# AI SOC Platform - Client Configuration

client:
  agent_id: "auto"  # Auto-generate or specify
  server_endpoint: "http://localhost:8080"
  api_key: "${AI_SOC_API_KEY}"
  reconnect_interval: 30
  heartbeat_interval: 60
  
log_forwarding:
  enabled: true
  batch_size: 100
  flush_interval: 5
  compression: true
  encryption: true
  
log_sources:
  system_logs:
    enabled: true
    priority: "high"
  security_logs:
    enabled: true
    priority: "critical"
  application_logs:
    enabled: true
    priority: "medium"
  attack_logs:
    enabled: true
    priority: "critical"
    
windows:
  event_logs:
    - "Security"
    - "System" 
    - "Application"
    - "Microsoft-Windows-Sysmon/Operational"
    - "Microsoft-Windows-PowerShell/Operational"
    - "Microsoft-Windows-Windows Defender/Operational"
  wmi_enabled: true
  
linux:
  log_files:
    - "/var/log/auth.log"
    - "/var/log/syslog"
    - "/var/log/kern.log"
    - "/var/log/audit/audit.log"
  auditd_enabled: true

ebpf:
  enabled: true
  monitoring:
    syscalls: true
    network: true
    file_access: true
    process_exec: true
  fallback_to_proc: true
  
filtering:
  enabled: true
  exclude_patterns:
    - ".*DEBUG.*"
    - ".*routine maintenance.*"
  include_patterns:
    - ".*SECURITY.*"
    - ".*ERROR.*"
    - ".*CRITICAL.*"
    
performance:
  max_memory_mb: 512
  max_cpu_percent: 20
  queue_size: 10000
  
attack_agent:
  execution_logging: true
  command_logging: true
  result_logging: true
  process_monitoring: true
  command_execution: true

containers:
  enabled: true
  max_containers: 5
  log_forwarding: true
  auto_cleanup: true
  cleanup_after_hours: 24
  preserve_golden_images: true
  
  # Container templates for different attack scenarios
  templates:
    windows_endpoint:
      image: "mcr.microsoft.com/windows/servercore:ltsc2019"
      platform: "windows"
      memory_limit: "2g"
      cpu_limit: "1.0"
      
    linux_server:
      image: "ubuntu:22.04"
      platform: "linux"
      memory_limit: "1g"
      cpu_limit: "0.5"
      
    web_application:
      image: "nginx:alpine"
      platform: "linux"
      memory_limit: "512m"
      cpu_limit: "0.3"
      
    database_server:
      image: "mysql:8.0"
      platform: "linux"
      memory_limit: "1g"
      cpu_limit: "0.5"
