# Attack Orchestrator Configuration
attack_orchestrator:
  enabled: true
  mode: "production"
  max_concurrent_attacks: 5
  attack_timeout: 300
  cleanup_interval: 3600

# AI Configuration
ai:
  openai_api_key: "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"
  model: "gpt-3.5-turbo"
  temperature: 0.7
  max_tokens: 1000

# Attack Configuration
attacks:
  credential_dumping:
    enabled: true
    techniques: ["lsass", "sam", "registry", "shadow"]
  
  network_scanning:
    enabled: true
    ports: [22, 80, 443, 3389, 5985, 5986]
  
  container_attacks:
    enabled: true
    docker_support: true

# Logging
logging:
  level: "INFO"
  file: "attack_orchestrator.log"
  max_size: "10MB"
  backup_count: 5
