# Windows Client Agent Configuration - Full SOC Platform
# Complete log collection for comprehensive security monitoring

windows:
  event_logs: ['Security', 'System', 'Application', 'Setup', 'ForwardedEvents']
  wmi_enabled: true
  firewall_logs: true
  iis_logs: true
  powershell_logs: true

linux:
  log_files: [
    '/var/log/syslog',
    '/var/log/auth.log', 
    '/var/log/kern.log',
    '/var/log/secure',
    '/var/log/messages',
    '/var/log/audit/audit.log',
    '/var/log/firewall.log',
    '/var/log/apache2/access.log',
    '/var/log/apache2/error.log',
    '/var/log/nginx/access.log',
    '/var/log/nginx/error.log'
  ]
  auditd_enabled: true

# Comprehensive monitoring settings
heartbeat_interval: 30
log_forwarding_interval: 5
network_discovery_interval: 300
process_monitoring: true
file_monitoring: true
network_monitoring: true

# Server endpoint
server_endpoint: "http://15.207.6.45:8080"
